CREATE TABLE MEMBER (
    USERID VARCHAR2(50) NOT NULL,
    USERPW VARCHAR2(50) NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100),
    REGDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATEDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY(USERID)
)

SELECT * FROM MEMBER;

--drop table member;