-- 순번 생성을 위한 sequences 테이블
create sequence tmp_seqs start with 1 increment by 1

-- BOARD TABLE
CREATE TABLE TBL_BOARD
(
    BNO NUMBER DEFAULT TMP_SEQS.NEXTVAL NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    "CONTENT" CLOB NULL,
    WRITER VARCHAR2(50) NOT NULL,
    REGDATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    VIEWCNT NUMBER DEFAULT 0,
    PRIMARY KEY (BNO)
);
