-- ���̺� ��ȸ
select * from BIZ_BOARD_FAVORITE

-- ���̺� ����
CREATE TABLE BIZ_BOARD_FAVORITE(
	BIZ_NUM_FAVORITE	NUMBER(10),		-- ä����� ��� ��ȣ
	BIZ_USER_FAVORITE	VARCHAR2(50),	-- ���ã�� ��� ���� ID
	CONSTRAINT FK_BIZ_BOARD_FAVORITE FOREIGN KEY(BIZ_NUM_FAVORITE)	-- BIZ_NUM_FAVORITE�� �ܷ�Ű�� ����
	REFERENCES BIZ_BOARD(BIZ_NUM) ON DELETE CASCADE	-- BIZ_BOARD�� BIZ_NUM�� ����Ű�� ���� BIZ_BOARD���� ������ ���� ������
);

-- ���̺� ����
DROP TABLE BIZ_BOARD_FAVORITE;
